# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Gedachtes
tagline:          'Dieser Blog ist der wahnhafte Fehlversuch Gedanken zu debuggen und zum scheitern verurteilt.'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://gedacht.es
baseurl:          /

author:
  name:           'Bubl'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gedachtes/gedachtes.github.io/
